# This file was generated by GoReleaser. DO NOT EDIT.
cask "praxis" do
  version "1.11.0"

  on_macos do
    on_arm do
      sha256 "420368ce81e6312cf8f845002761ddf54ac599b5b2b2cb3f311726e4d2bbd836"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_darwin_arm64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_darwin_arm64", target: "praxis"
    end
    on_intel do
      sha256 "ffb021fd261df2a068a07360ffd3a643c4bb819bcf0480fae6d8b7cf639e985f"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_darwin_amd64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_darwin_amd64", target: "praxis"
    end
  end
  on_linux do
    on_arm do
      sha256 "a2a0b6ef864b3849583da3e1d530311ff97bef36961ca0c8828fd8c1149bd092"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_linux_arm64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_linux_arm64", target: "praxis"
    end
    on_intel do
      sha256 "154b190050994d937e5f9c9f29951e3477b1f12ba14e636800574680332847a6"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_linux_amd64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_linux_amd64", target: "praxis"
    end
  end

  name "praxis"
  desc "Bring Praxis cloud capabilities to any local AI host"
  homepage "https://facets.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
    # Land the pre-login "getting started" skill so the user's AI host
    # knows what Praxis is + how to sign up / log in, without waiting for a
    # first `praxis` run. Best-effort: never fail `brew install`, and the
    # binary's own first-run auto-install covers non-brew installs.
    system_command "#{HOMEBREW_PREFIX}/bin/praxis", args: ["setup"], must_succeed: false
  end

  # No zap stanza required
end
