# This file was generated by GoReleaser. DO NOT EDIT.
cask "praxis" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "98fd48670f3cde8ea35fc11c55c734b9f00422d1c396360c667668e5c5e1f666"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_darwin_amd64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_darwin_amd64", target: "praxis"
    end
    on_arm do
      sha256 "d4e79f0c4844e9778a5b929c2b13447f7ac107ee283f3f851f38765ed6b8b466"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_darwin_arm64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_darwin_arm64", target: "praxis"
    end
  end

  on_linux do
    on_intel do
      sha256 "9bab4c1e4dbabd92f119721004a27131f8be32c7c9f07af22bcbd2d2b9d0aaf4"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_linux_amd64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_linux_amd64", target: "praxis"
    end
    on_arm do
      sha256 "7b4a4128d43b02866be86a5076d2244161aa36bc1044cb5d66b9e5321e0773d0"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_linux_arm64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_linux_arm64", target: "praxis"
    end
  end

  name "praxis"
  desc "Bring Praxis cloud capabilities to any local AI host"
  homepage "https://askpraxis.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

end
