# This file was generated by GoReleaser. DO NOT EDIT.
cask "praxis" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "1593b80c8d525b6607142a4954f417c95af30c9183cbcfb76318058c29fdd727"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_darwin_amd64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_darwin_amd64", target: "praxis"
    end
    on_arm do
      sha256 "3bbf3b3832a7b6d7da8e4a4200417e8d32cfd00cdfd014e5293a2e0640a73bfe"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_darwin_arm64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_darwin_arm64", target: "praxis"
    end
  end

  on_linux do
    on_intel do
      sha256 "b295929f464002f69729f8da9dde92420f863d7ce84f114172b01002756eb92f"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_linux_amd64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_linux_amd64", target: "praxis"
    end
    on_arm do
      sha256 "36322976e4d577972e99ab6fbc83c54022f3b38425cdd0a17b35821afc2da1ab"
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v#{version}/praxis_linux_arm64",
        verified: "github.com/Facets-cloud/praxis-cli/"
      binary "praxis_linux_arm64", target: "praxis"
    end
  end

  name "praxis"
  desc "Bring Praxis cloud capabilities to any local AI host"
  homepage "https://askpraxis.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required

end
