# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Praxis < Formula
  desc "Bring Praxis cloud capabilities to any local AI host"
  homepage "https://askpraxis.ai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.1.0/praxis_darwin_amd64"
      sha256 "6584ee92fed5ac2f8dc4dc9c64d86ebfae92519406430cf85e6e111565770729"

      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.1.0/praxis_darwin_arm64"
      sha256 "e62f2e0eba2c8ab0afd75c623618ba2cccaf07eef6fb1b16293f87409ed2ad72"

      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.1.0/praxis_linux_amd64"
      sha256 "45b6c0814c3afc6b075c4affc5cf1979a6a8715cefe945dd5e9be57e147cdf97"
      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.1.0/praxis_linux_arm64"
      sha256 "b97789f79b1c0315baf237d2af0e45bc3cf9ee0947fdf1e05400c4245699bc90"
      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
  end

  test do
    system "#{bin}/praxis", "version"
  end
end
