# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Praxis < Formula
  desc "Bring Praxis cloud capabilities to any local AI host"
  homepage "https://askpraxis.ai"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.4.0/praxis_darwin_amd64"
      sha256 "77e0e6450d2a7cfc418cc907fe694378912c0951fa665e39c6dc48021a006bb3"

      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.4.0/praxis_darwin_arm64"
      sha256 "50b1efdeeaedd278d7f0a297e467381556c45098f693ebfd9f99833ceed4f178"

      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.4.0/praxis_linux_amd64"
      sha256 "866aa454f0ae55bfa519ae45be44d5a4f128cc156c4ac10f5662ea2cb7646ef5"
      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.4.0/praxis_linux_arm64"
      sha256 "4fd1e79db251b98d1fe657a53b0736b87ec43fa20b567599044913d5a913c99c"
      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
  end

  test do
    system "#{bin}/praxis", "version"
  end
end
