# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Praxis < Formula
  desc "Bring Praxis cloud capabilities to any local AI host"
  homepage "https://askpraxis.ai"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.8.0/praxis_darwin_amd64"
      sha256 "7aee650584963cc6df3a3caf87add064c49d79aae95f121562c8d9fa2d87c05b"

      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.8.0/praxis_darwin_arm64"
      sha256 "30630c07486735fb359e793dc005a90e6283ae4649a099974a32c7a20457804f"

      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.8.0/praxis_linux_amd64"
      sha256 "db622141e6bf1a2bbf110c179a38e96caf1fe2d58694ce486dee2e045ef61c77"
      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Facets-cloud/praxis-cli/releases/download/v0.8.0/praxis_linux_arm64"
      sha256 "a1c1855b0f6ae9e5f8bc2b2864b2063dc5e6b09d4e008c3c0abe22f4dc27ebf2"
      define_method(:install) do
        # Raw-binary assets shipped via GitHub Releases arrive with mode
        # 0644 (GitHub strips the executable bit on upload). chmod before
        # the test-step or install call tries to exec the binary.
        binary = Dir["*"].find { |f| File.file?(f) }
        File.chmod(0755, binary)
        bin.install binary => "praxis"
        generate_completions_from_executable(bin/"praxis", "completion")
      end
    end
  end

  test do
    system "#{bin}/praxis", "version"
  end
end
